export type RootStackParamList = {
  Verification: { onVerification: () => void; email: string };
  Auth: undefined;
  Onboarding: undefined;
  ResetPassword: { email: string } | undefined;
  CreateNewPassword: undefined;
  SuccessChanged: undefined;
  Bookshelf: undefined;
  Organaizer: undefined;
  Meeting: undefined;
  ProfileScreen: undefined;
  ProfileSettings: undefined;
  Language: undefined;
  Notifications: undefined;
  ChangePassword: undefined;
  ReadingSpace: { bookId: string; saveNote: string; saveBookmark: string };
  Tabs: undefined;
  BookmarkScreen: undefined;
  NoteScreen: undefined;
  TabsNote: { bookId: string; saveNote: string; saveBookmark: string };
};
